# Generated by Django 4.1.13 on 2025-07-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
